version: '3.2'

volumes:
  npms:
  data:

networks:
  internal:
  external:

services:
  hls:
    image: avalonmediasystem/nginx:minio
    environment:
      - AVALON_DOMAIN=http://avalon:3000
      - AVALON_STREAMING_BUCKET_URL=http://minio:9000/derivatives/
    ports:
      - '8880:80'
    networks:
      internal:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:

  avalon: &avalon
    image: avalonmediasystem/avalon:7.0-slim-dev-20200106
    build: .
    command: bash -c "/docker_init.sh && rails server -b 0.0.0.0"
    depends_on:
      - redis
      - hls
      - minio
    environment:
      - APP_NAME=avalon
      - AVALON_BRANCH=develop
      - SETTINGS__DOMAIN=http://localhost:3000
      - BUNDLE_FLAGS=--with development postgres --without production test
      - ENCODE_WORK_DIR=/tmp
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://postgres@db/avalon
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=development
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SOLR_URL=http://solr:8983/solr/avalon
      - AWS_REGION=us-east-1
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__MINIO__ENDPOINT=http://minio:9000
      - SETTINGS__MINIO__PUBLIC_HOST=http://localhost:9000
      - SETTINGS__MINIO__ACCESS=minio
      - SETTINGS__MINIO__SECRET=minio123
      - SETTINGS__ENCODING__MASTERFILE_BUCKET=masterfiles
      - SETTINGS__ENCODING__DERIVATIVE_BUCKET=derivatives
      - SETTINGS__DROPBOX__PATH=s3://masterfiles/dropbox/
      - SETTINGS__DROPBOX__UPLOAD_URI=s3://masterfiles/dropbox/
      - SETTINGS__MASTER_FILE_MANAGEMENT__PATH=s3://preserves/
      - SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=MOVE
      - SETTINGS__STREAMING__CONTENT_PATH=/derivatives/
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - env_ldap_user=${LDAP_USER}
      - env_ldap_password=${LDAP_PASSWORD}
    volumes:
      - .:/home/app/avalon
      - npms:/home/app/avalon/node_modules
    ports:
      - '3000:3000'
    networks:
      internal:
      external:
    stdin_open: true
    tty: true

  worker:
    <<: *avalon
    command: dumb-init -- bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    ports: []

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - data:/data
    ports:
      - 9000:9000
    networks:
      internal:
      external:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb -p myminio/masterfiles myminio/derivatives;
      /usr/bin/mc policy set download myminio/derivatives;
      exit 0;
      "
    networks:
      internal:
