version: '3.2'

volumes:
  streaming:
  database:
  fedora:
  work:
  solr:
  npms:

networks:
  internal:
  external:

services:
  db: &db-avalon
    image: postgres:10-alpine
    volumes:
      - database:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
    networks:
      internal:
  db-test:
    <<: *db-avalon
    volumes: []

  fedora: &fedora
    image: avalonmediasystem/fedora:4.7.5
    depends_on:
      - db
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=-Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  fedora-test:
    <<: *fedora
    volumes: []

  solr: &solr
    image: solr:6.6.4-alpine
    volumes:
      - ./solr/config:/opt/solr/avalon_conf
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  solr-test:
    <<: *solr
    volumes:
      - ./solr/config:/opt/solr/avalon_conf

  matterhorn:
    image: avalonmediasystem/matterhorn
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    networks:
      internal:
  hls:
    image: avalonmediasystem/nginx
    environment:
      - AVALON_DOMAIN=http://avalon:3000
    volumes:
      - streaming:/data
    ports:
      - '8880:80'
    networks:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:
  redis-test:
    <<: *redis

  avalon: &avalon
    image: avalonmediasystem/avalon:6.x-slim-dev
    build: .
    command: bash -c "/docker_init.sh && rails server -b 0.0.0.0"
    depends_on:
      - db
      - fedora
      - solr
      - redis
      - matterhorn
    environment:
      - APP_NAME=avalon
      - AVALON_BRANCH=develop
      - BUNDLE_FLAGS=--with development postgres --without production test
      - SETTINGS__DOMAIN=http://localhost:3000
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://postgres@db/avalon
      - SETTINGS__DROPBOX__PATH=/masterfiles
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=development
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - .:/home/app/avalon
      - ./masterfiles:/masterfiles
      - npms:/home/app/avalon/node_modules
    ports:
      - '3000:3000'
      - '3001:3001'
    networks:
      internal:
      external:
    stdin_open: true
    tty: true

  test:
    <<: *avalon
    command: >
      bash -c "/docker_init.sh && tail -f /dev/null"
    depends_on:
      - db-test
      - fedora-test
      - solr-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://postgres@db-test/avalon
      - REDIS_HOST=redis-test
      - FEDORA_URL=http://fedora-test:8080/fedora/rest
      - SOLR_URL=http://solr-test:8983/solr/avalon
      - RAILS_ENV=test
      - BUNDLE_FLAGS=--with aws test postgres --without production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    ports: []
