development:
  user: <%= ENV['FEDORA_USER'] %> 
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL'] %>:<%= ENV['FEDORA_PORT'] %>/fcrepo/rest/<%= ENV['FEDORA_NAMESPACE'] %>
  base_path: /dev
test:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL'] %>:<%= ENV['FEDORA_PORT'] %>/fcrepo/rest/<%= ENV['FEDORA_NAMESPACE'] %>
  base_path: /test
production:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWORD'] %>
  url: <%= ENV['FEDORA_URL'] %>:<%= ENV['FEDORA_PORT'] %>/fcrepo/rest/<%= ENV['FEDORA_NAMESPACE'] %>
  base_path: /prod