development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: {{FEDORA_USER_YML}}
  password: {{FEDORA_PASSWORD_YML}}
  url: http://{{FEDORA_HOST_YML}}:{{FEDORA_PORT_YML}}/fedora/rest
  base_path: /{{FEDORA_BASE_PATH_YML}}