development:
  user: <%= ENV['FCREPO_USER'] %> 
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>:<%= ENV['FCREPO_PORT'] %>/fedora4/rest
  base_path: /dev
test:
  user: <%= ENV['FCREPO_USER'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>:<%= ENV['FCREPO_PORT'] %>/fedora4/rest
  base_path: /test
production:
  user: <%= ENV['FCREPO_USER'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>:<%= ENV['FCREPO_PORT'] %>/fedora4/rest
  base_path: /prod
