development:
  user: <%= ENV['env_fedora_user'] %> 
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest
  base_path: /<%= ENV['env_fedora_base_path'] %>
test:
  user: <%= ENV['env_fedora_user'] %>
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest
  base_path: /<%= ENV['env_fedora_base_path'] %>
production:
  user: <%= ENV['env_fedora_user'] %>
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest
  base_path: /<%= ENV['env_fedora_base_path'] %>
