development:
  user: <%= ENV['env_fedora_user'] %> 
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest/<%= ENV['env_fedora_namespace'] %>
  base_path: /dev
test:
  user: <%= ENV['env_fedora_user'] %>
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest/<%= ENV['env_fedora_namespace'] %>
  base_path: /test
production:
  user: <%= ENV['env_fedora_user'] %>
  password: <%= ENV['env_fedora_password'] %>
  url: <%= ENV['env_fedora_url'] %>:<%= ENV['env_fedora_port'] %>/fcrepo/rest/<%= ENV['env_fedora_namespace'] %>
  base_path: /prod
