name: 'TAMU - Avalon Media System' # used in page titles
domain:
  host: <%= ENV['env_avalon_hostname'] %>
  port: <%= ENV['env_avalon_port'] %>
  protocol: <%= ENV['env_avalon_protocol'] %>
dropbox:
  path: <%= ENV['env_dropbox_path'] %>
  upload_uri: <%= ENV['env_dropbox_upload_uri'] %>
encoding:
  engine_adapter: ffmpeg
  presets_path: config/ffmpeg_presets.yml
  working_file_path: '<%= ENV['env_encoding_working_file_path'] %>'  
mediainfo:
  path: '/usr/bin/mediainfo'
ffmpeg:
  path: '/usr/bin/ffmpeg'
email:
  mailer: :smtp
  config:  
    address: 'relay.tamu.edu'
    port: 25
    enable_starttls_auto: false
  comments: '<%= ENV['env_email_comments'] %>'
  notification: '<%= ENV['env_email_notification'] %>'
  support: '<%= ENV['env_email_support'] %>'
solr:
  configset: avalon
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: avalon
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:
zookeeper:
  connection_str: "localhost:9983/configs"
streaming:
  server: :nginx
  http_base: '<%= ENV['env_streaming_http_base'] %>'
  stream_token_ttl: 20 #minutes
  content_path: '<%= ENV['env_streaming_content_path'] %>'
  rtmp_base: '<%= ENV['env_streaming_rtmp_base'] %>'
  default_quality: 'auto'
redis:
  host: <%= ENV['env_redis_host'] %>
  port: <%= ENV['env_redis_port'] %>
master_file_management:
  strategy: 'delete' #'delete', or 'move' (for move uncomment and configure next line)
  path: '/mnt/avalon/avalon-archive'  
groups:
  system_groups: [administrator, group_manager, manager]
bib_retriever:
  default:
    protocol: sru
    url: http://zgate.example.edu:9000/exampledb
    query: rec.id='%s'
    retriever_class: 'Avalon::BibRetriever::SRU'
    retriever_class_require: 'avalon/bib_retriever/sru'
controlled_vocabulary:
  path: config/controlled_vocabulary.yml
encode_throttling:
  create_jobs_throttle_threshold: 2
  create_jobs_spacing: 5
  update_jobs_throttle_threshold: 3
  update_jobs_spacing: 10
timeliner:
  timeliner_url: <%= ENV['env_timeliner_url'] %> 
auth:
  registerable: true
  configuration:
    <% if ENV['LTI_AUTH_KEY'] %>
    - :name: Avalon Lti OAuth
      :provider: :lti
      :hidden: true
      :params:
        :oauth_credentials:
          <%= ENV['LTI_AUTH_KEY'] %>: <%= ENV['LTI_AUTH_SECRET'] %>
    <% end %>
    <% if ENV['env_ldap_password'] %>    
    - :name: TAMU LDAP
      :logo: auth_provider_logo.png
      :provider: :ldap
      :params:
        :method: :ssl
        :uid: sAMAccountName
        :host: adsdc1.library.tamu.edu
        :port: 636
        :bind_dn: <%= ENV['env_ldap_user'] %>
        :password: <%= ENV['env_ldap_password'] %>
        :base: OU=UserAccounts,DC=library,DC=tamu,DC=edu
    <% end %>
# google_analytics_tracking_id: "someid"
